const colors = {
  black: "#102A43",
  white: "#ffffff",
  primary: "#FF8C42",
  "primary-dark": "#E33532",
  "secondary-light": "#A0D96B",
  secondary: "#5CBF8B",
  "secondary-dark": "#039B9A",
  "secondary-darkest": "#085169",
  transparent: "transparent",
  grey: {
    "100": "#F0F4F8",
    "200": "#D9E2EC",
    "300": "#BCCCDC",
    "400": "#9FB3C8",
    "500": "#829AB1",
    "600": "#627D98",
    "700": "#486581",
    "800": "#334E68",
    "900": "#243B53",
  },
}
module.exports = {
  theme: {
    fontFamily: {
      sans: [
        "Fira Sans",
        "-apple-system",
        "BlinkMacSystemFont",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
      display: [
        "Roboto Slab",
        "Fira Sans",
        "-apple-system",
        "BlinkMacSystemFont",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
    },
    colors,
    extend: {},
  },
  variants: {},
  plugins: [],
}
